-- schema.sql for Supabase (example)
-- Run this in Supabase SQL editor to create a 'bills' table.
CREATE TABLE IF NOT EXISTS bills (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users (id),
  date text,
  month text,
  kwh numeric,
  cost numeric,
  total numeric,
  inserted_at timestamp with time zone DEFAULT now()
);
